dataset:
  train_fname: 'n_alternates_1+_global_random_split_x_train.csv'
  val_fname: 'n_alternates_1+_global_random_split_x_val.csv'
  max_chars: 32
tokenizer:
  name: unigram_tokenizer
  maxlen: 32
  num_words: null
train_sampler:
  name: sampler_v2
  batch_size: 16
  n_negatives: 1
  neg_samples_size: 30
  shuffle: true
val_sampler:
  name: sampler_v2
  batch_size: 16
  n_negatives: 3
  neg_samples_size: 30
  shuffle: true
model:
  name: 'siamese_net_v2'
  encoder: 'lstm1'
criterion:
  name: 'binary_crossentropy'
optimizer:
  name: 'adam'
  lr: 0.001
metrics:
  accuracy: 'primary'
  AUC: 'primary'
training:
  num_epochs: 20
  num_workers: 8
  multi_process: false
