dataset:
  name: 'unbiased_preshuffled_dataset-string-similarity-global-train-original.csv'
#  train_path: 'data/train.csv'
#  val_path: 'data/val.csv'
model:
  name: 'similarity_v2'
  num_classes: 2
criterion:
  name: 'cross_entropy_loss'
optimizer:
  name: 'adam'
  lr: 0.001
training:
  batch_size: 128
  num_epochs: 30
  num_workers: 8
metrics:
  accuracy: 'primary'