dataset:
  train_fname: 'n_alternates_1+_latin_stratified_split_x_train.csv'
  val_fname: 'n_alternates_1+_latin_stratified_split_x_val.csv'
  max_chars: 32
tokenizer:
  name: unigram_tokenizer
  maxlen: 32
train_sampler:
  name: sampler_v2
  batch_size: 16
  n_negatives: 3
  neg_samples_size: 30
  shuffle: true
val_sampler:
  name: sampler_v2
  batch_size: 16
  n_negatives: 3
  neg_samples_size: 30
  shuffle: true
model:
  name: 'siamese_net'
  encoder: 'lstm1'
criterion:
  name: 'binary_crossentropy'
optimizer:
  name: 'adam'
  lr: 0.001
metrics:
  accuracy: 'primary'
  AUC: 'primary'
training:
  num_epochs: 30
  num_workers: 8
  multi_process: false
